### ISSUE TITLE
Grey bar

### ISSUE THREAD

**Issue by lyhonlam** [Yoctillion/Viramate-Fix#2]
Since few days ago I got this huge grey bar whenever Viramate-fix enabled . Could you take a look ?

![screenshot_441](https://user-images.githubusercontent.com/32795659/31576006-c3d242fc-b11c-11e7-8dbd-d84faddc8e02.png)

**Comment by Yoctillion** [comment]
Press `Ctrl`+`Shift`+`I` to open the `Developer Tools`, then switch to the `Console` tab and run the script below
```Javascript
$($(".BH29UqMRA7nnSLfpZ1Yxk")[0]).click()
````
If the grey area is still visible, try to run the script again.

**Comment by lyhonlam** [comment]
Thank you for your help :) It all good now 👍
