### ISSUE TITLE
存在弹窗强制顶置现象，每次都得往上拉

### ISSUE THREAD

**Issue by 03170508** [Yoctillion/Viramate-Fix#4]
![qq 20180803030719](https://user-images.githubusercontent.com/42045250/43605295-73471c9c-96ca-11e8-82fe-9de2bc7c9516.jpg)
![1](https://user-images.githubusercontent.com/42045250/43605369-af366294-96ca-11e8-930d-4551274a6f2a.png)

**Comment by Yoctillion** [comment]
Fixed in e2d9c7b11de517d70efbeb055be870f26b5d9f10
