### ISSUE TITLE
Viramate Fix Issues with Choosing Support Summon, etc

### ISSUE THREAD

**Issue by mikkiteh** [Yoctillion/Viramate-Fix#5]
Greetings,

I encountered some minor issues while using this fix. I've seen in the issues section someone already posting this, but I will reposting it just in case.

When I was choosing support summon, the summon confirmation didn't appear in the middle, but instead on the top. I tried to disable the Viramate Fix, and the issue is cleared so I assume the main problem was in the Fix.

Here's when I was choosing support summon with Viramate Fix

![2](https://user-images.githubusercontent.com/42292789/43990551-d43592d2-9d86-11e8-96a7-0d72124f3d97.PNG)

And here's when I disabled it.
![1](https://user-images.githubusercontent.com/42292789/43990550-d27e931c-9d86-11e8-9e09-237189b66a6d.PNG)

Also, the problem isn't only when you choose support summon, but also when you trade in shop or Casino. Here's the screenshot when I trade something in casino's shop.
![3](https://user-images.githubusercontent.com/42292789/43990626-0df8351e-9d88-11e8-8a50-6a62fba38e65.PNG)

I know it's only minor issues, but I hope this problem is cleared soon. This Viramate Fix is too good to not be used because of this.

**Comment by Yoctillion** [comment]
Fixed in e2d9c7b11de517d70efbeb055be870f26b5d9f10
